export const ciudadesImportantes = [
    "Adelaide",
    "Amberes",
    "Amsterdam",
    "Aspen",
    "Atenas",
    "Auckland",
    "Bagan",
    "Banff",
    "Bangkok",
    "Barcelona",
    "Beijing",
    "Berlín",
    "Bern",
    "Bregenz",
    "Brisbane",
    "Bruselas",
    "Budapest",
    "Buenos Aires",
    "Busan",
    "Calgary",
    "Cairo",
    "Canberra",
    "Chengdu",
    "Chicago",
    "Chiang Mai",
    "Christchurch",
    "Copenhague",
    "Crans-Montana",
    "Cuenca",
    "Daejeon",
    "Darwin",
    "Davos",
    "Dubái",
    "Dublín",
    "Edimburgo",
    "Edmonton",
    "Eindhoven",
    "El Cairo",
    "Estambul",
    "Estocolmo",
    "Frankfurt",
    "Fukuoka",
    "Ginebra",
    "Gold Coast",
    "Granada",
    "Graz",
    "Gstaad",
    "Guangzhou",
    "Gwangju",
    "Halifax",
    "Hangzhou",
    "Hanoi",
    "Harbin",
    "Helsinki",
    "Hiroshima",
    "Ho Chi Minh City",
    "Hobart",
    "Hong Kong",
    "Honolulu",
    "Hua Hin",
    "Incheon",
    "Interlaken",
    "Inverness",
    "Iqaluit",
    "Istanbul",
    "Jeonju",
    "Jerusalén",
    "Johannesburgo",
    "Kobe",
    "Kolkata",
    "Krabi",
    "Kunming",
    "Kyoto",
    "La Haya",
    "Lago Inle",
    "Lake Tahoe",
    "Las Vegas",
    "Lhasa",
    "Linz",
    "Lisboa",
    "Londres",
    "Los Ángeles",
    "Luang Prabang",
    "Lucerna",
    "Lyon",
    "Macao",
    "Madrid",
    "Málaga",
    "Melbourne",
    "México D.F.",
    "Miami",
    "Milán",
    "Monaco",
    "Montreal",
    "Moscow",
    "Mumbai",
    "Múnich",
    "Nagoya",
    "Nairobi",
    "Nanchang",
    "Nanjing",
    "Nara",
    "Nha Trang",
    "Niza",
    "Nueva Delhi",
    "Nueva York",
    "Osaka",
    "Oslo",
    "Ottawa",
    "Pakse",
    "Paphos",
    "París",
    "Pattaya",
    "Pekín",
    "Phnom Penh",
    "Phuket",
    "Praga",
    "Queenstown",
    "Quito",
    "Reikiavik",
    "Río de Janeiro",
    "Roma",
    "Rotorua",
    "San Francisco",
    "San Moritz",
    "San Petersburgo",
    "Sapporo",
    "Seúl",
    "Seychelles",
    "Shanghai",
    "Shanghái",
    "Siem Reap",
    "Sidney",
    "Singapur",
    "Sídney",
    "Sihanoukville",
    "Sídney",
    "Sofía",
    "St. John's",
    "Suwon",
    "Sydney",
    "Tallin",
    "Telluride",
    "Tiflis",
    "Tokio",
    "Toronto",
    "Ulaanbaatar",
    "Utrecht",
    "Vancouver",
    "Varsavia",
    "Viena",
    "Vientiane",
    "Vilna",
    "Villa Regina",
    "Winnipeg",
    "Yellowknife",
    "Yokohama",
    "Zermatt",
    "Zúrich",
    
  ];
  